lib: [
  "_build/install/default/lib/Game/META"
  "_build/install/default/lib/Game/dune-package"
  "_build/install/default/lib/Game/game.a"
  "_build/install/default/lib/Game/game.cma"
  "_build/install/default/lib/Game/game.cmi"
  "_build/install/default/lib/Game/game.cmt"
  "_build/install/default/lib/Game/game.cmx"
  "_build/install/default/lib/Game/game.cmxa"
  "_build/install/default/lib/Game/game.ml"
  "_build/install/default/lib/Game/game__Player.cmi"
  "_build/install/default/lib/Game/game__Player.cmt"
  "_build/install/default/lib/Game/game__Player.cmti"
  "_build/install/default/lib/Game/game__Player.cmx"
  "_build/install/default/lib/Game/game__Window.cmi"
  "_build/install/default/lib/Game/game__Window.cmt"
  "_build/install/default/lib/Game/game__Window.cmti"
  "_build/install/default/lib/Game/game__Window.cmx"
  "_build/install/default/lib/Game/opam"
  "_build/install/default/lib/Game/player.ml"
  "_build/install/default/lib/Game/player.mli"
  "_build/install/default/lib/Game/window.ml"
  "_build/install/default/lib/Game/window.mli"
]
libexec: [
  "_build/install/default/lib/Game/game.cmxs"
]
doc: [
  "_build/install/default/doc/Game/README.md"
]
